# Generated by Django 4.2 on 2023-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Стартовое описание', max_length=5000),
        ),
    ]
